import React from 'react';
import { useTranslation } from '@/hooks/useTranslation';
import { useFarmer } from '@/contexts/FarmerContext';
import { getAlerts } from '@/services/alertService';

export default function Reports() {
  const { t } = useTranslation();
  const { farmer, cropResult, diseaseResult, yieldResult, healthResult, economicsResult } = useFarmer();
  const alerts = getAlerts(farmer?.id);

  const generateText = () => {
    let report = '=== AgriAdvisory - Comprehensive Farm Report ===\n\n';
    
    report += '--- Farmer Details ---\n';
    if (farmer) {
      report += `Name: ${farmer.name}\nState: ${farmer.state}\nDistrict: ${farmer.district}\nMandal: ${farmer.mandal}\nLand: ${farmer.landSize} acres\nSoil: ${farmer.soilType}\nEmail: ${farmer.email}\nPhone: ${farmer.phone}\n`;
    } else report += 'Not registered\n';

    report += '\n--- Crop Recommendation ---\n';
    if (cropResult) report += `Crop: ${cropResult.crop}\nConfidence: ${cropResult.confidence}%\nRisk: ${cropResult.risk}\n`;
    else report += 'Not analyzed\n';

    report += '\n--- Disease Analysis ---\n';
    if (diseaseResult) report += `Disease: ${diseaseResult.disease}\nConfidence: ${diseaseResult.confidence}%\nSeverity: ${diseaseResult.severity}\nTreatments: ${diseaseResult.treatments.join('; ')}\n`;
    else report += 'Not analyzed\n';

    report += '\n--- Yield Estimate ---\n';
    if (yieldResult) report += `Estimated: ${yieldResult.estimatedYield} q\nRange: ${yieldResult.yieldRange[0]}-${yieldResult.yieldRange[1]} q\nRisk: ${yieldResult.risk}\n`;
    else report += 'Not analyzed\n';

    report += '\n--- Health Score ---\n';
    if (healthResult) report += `Score: ${healthResult.score}/100\n`;
    else report += 'Not calculated\n';

    report += '\n--- Economics ---\n';
    if (economicsResult) report += `Total Cost: ₹${economicsResult.totalCost}\nRevenue: ₹${economicsResult.revenue}\nProfit: ₹${economicsResult.profit}\nRisk: ${economicsResult.profitRisk}\n`;
    else report += 'Not calculated\n';

    report += '\n--- Alerts ---\n';
    if (alerts.length) alerts.forEach(a => report += `[${a.priority}] ${a.type}: ${a.message}\n`);
    else report += 'No alerts\n';

    report += '\n\nGenerated by AgriAdvisory AI System';
    return report;
  };

  const handleDownload = () => {
    const blob = new Blob([generateText()], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `AgriAdvisory_Report_${farmer?.name || 'Farmer'}_${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
    <div className="border-b border-border pb-3 mb-3 last:border-0">
      <h3 className="text-sm font-semibold text-primary mb-2">{title}</h3>
      {children}
    </div>
  );

  const Row = ({ label, value }: { label: string; value: string }) => (
    <div className="flex justify-between text-xs py-0.5">
      <span className="text-muted-foreground">{label}</span>
      <span className="font-medium text-foreground">{value}</span>
    </div>
  );

  return (
    <div className="max-w-3xl mx-auto">
      <h1 className="text-2xl font-bold text-foreground mb-1">{t('report.title')}</h1>
      <p className="text-sm text-muted-foreground mb-6">{t('report.subtitle')}</p>

      <div className="bg-card border border-border rounded-lg p-6 mb-4">
        <Section title="👤 Farmer Details">
          {farmer ? (
            <>
              <Row label="Name" value={farmer.name} />
              <Row label="State" value={farmer.state} />
              <Row label="District" value={farmer.district} />
              <Row label="Land" value={`${farmer.landSize} acres`} />
              <Row label="Soil" value={farmer.soilType} />
            </>
          ) : <p className="text-xs text-muted-foreground">Not registered yet</p>}
        </Section>

        <Section title="🌾 Crop Recommendation">
          {cropResult ? (
            <>
              <Row label="Recommended" value={cropResult.crop} />
              <Row label="Confidence" value={`${cropResult.confidence}%`} />
              <Row label="Risk" value={cropResult.risk} />
            </>
          ) : <p className="text-xs text-muted-foreground">Not analyzed</p>}
        </Section>

        <Section title="🦠 Disease Analysis">
          {diseaseResult ? (
            <>
              <Row label="Disease" value={diseaseResult.disease} />
              <Row label="Severity" value={diseaseResult.severity} />
              <Row label="Confidence" value={`${diseaseResult.confidence}%`} />
            </>
          ) : <p className="text-xs text-muted-foreground">Not analyzed</p>}
        </Section>

        <Section title="📊 Yield & Health">
          {yieldResult && <Row label="Estimated Yield" value={`${yieldResult.estimatedYield} quintals`} />}
          {healthResult && <Row label="Health Score" value={`${healthResult.score}/100`} />}
          {!yieldResult && !healthResult && <p className="text-xs text-muted-foreground">Not analyzed</p>}
        </Section>

        <Section title="💰 Economics">
          {economicsResult ? (
            <>
              <Row label="Total Cost" value={`₹${economicsResult.totalCost.toLocaleString('en-IN')}`} />
              <Row label="Revenue" value={`₹${economicsResult.revenue.toLocaleString('en-IN')}`} />
              <Row label="Profit" value={`₹${economicsResult.profit.toLocaleString('en-IN')}`} />
            </>
          ) : <p className="text-xs text-muted-foreground">Not calculated</p>}
        </Section>

        <Section title="🔔 Alerts">
          {alerts.length ? alerts.map(a => (
            <p key={a.id} className="text-xs text-foreground">• [{a.priority}] {a.message}</p>
          )) : <p className="text-xs text-muted-foreground">No alerts triggered</p>}
        </Section>
      </div>

      <button onClick={handleDownload} className="w-full py-2.5 rounded-md bg-primary text-primary-foreground font-semibold text-sm hover:opacity-90">
        📥 {t('common.download')} Report
      </button>
    </div>
  );
}
