// ============================================================
// Report Service — generates report text from stored data
// ============================================================

import { FarmerData, CropResult, DiseaseResult, YieldResult, HealthResult, EconomicsResult, AlertItem } from '@/models/types';

export interface ReportData {
  farmer: FarmerData | null;
  cropResult: CropResult | null;
  diseaseResult: DiseaseResult | null;
  yieldResult: YieldResult | null;
  healthResult: HealthResult | null;
  economicsResult: EconomicsResult | null;
  alerts: AlertItem[];
}

export function generateReportText(data: ReportData): string {
  let report = '=== AgriAdvisory - Comprehensive Farm Report ===\n\n';

  report += '--- Farmer Details ---\n';
  if (data.farmer) {
    const f = data.farmer;
    report += `Name: ${f.name}\nState: ${f.state}\nDistrict: ${f.district}\nMandal: ${f.mandal}\nLand: ${f.landSize} acres\nSoil: ${f.soilType}\nEmail: ${f.email}\nPhone: ${f.phone}\n`;
  } else report += 'Not registered\n';

  report += '\n--- Crop Recommendation ---\n';
  if (data.cropResult) report += `Crop: ${data.cropResult.crop}\nConfidence: ${data.cropResult.confidence}%\nRisk: ${data.cropResult.risk}\n`;
  else report += 'Not analyzed\n';

  report += '\n--- Disease Analysis ---\n';
  if (data.diseaseResult) report += `Disease: ${data.diseaseResult.disease}\nConfidence: ${data.diseaseResult.confidence}%\nSeverity: ${data.diseaseResult.severity}\nTreatments: ${data.diseaseResult.treatments.join('; ')}\n`;
  else report += 'Not analyzed\n';

  report += '\n--- Yield Estimate ---\n';
  if (data.yieldResult) report += `Estimated: ${data.yieldResult.estimatedYield} q\nRange: ${data.yieldResult.yieldRange[0]}-${data.yieldResult.yieldRange[1]} q\nRisk: ${data.yieldResult.risk}\n`;
  else report += 'Not analyzed\n';

  report += '\n--- Health Score ---\n';
  if (data.healthResult) report += `Score: ${data.healthResult.score}/100\n`;
  else report += 'Not calculated\n';

  report += '\n--- Economics ---\n';
  if (data.economicsResult) report += `Total Cost: ₹${data.economicsResult.totalCost}\nRevenue: ₹${data.economicsResult.revenue}\nProfit: ₹${data.economicsResult.profit}\nRisk: ${data.economicsResult.profitRisk}\n`;
  else report += 'Not calculated\n';

  report += '\n--- Alerts ---\n';
  if (data.alerts.length) data.alerts.forEach(a => report += `[${a.priority}] ${a.type}: ${a.message}\n`);
  else report += 'No alerts\n';

  report += '\n\nGenerated by AgriAdvisory AI System';
  return report;
}
